name = "Pretend"
uuid = "8ad1c615-040c-41b0-a18f-ae9e9fd09b5b"
authors = ["Tom Kwong <tk3369@gmail.com> and contributors"]
version = "0.2.0"

[deps]
ExprTools = "e2ba6199-217a-4e67-a87a-7c52f15ade04"
MacroTools = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09"

[compat]
ExprTools = "0.1"
MacroTools = "0.5"
julia = "1.1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
